const char *xdb_schema_sqlstr = 
"--\n"
"-- imess xdb schema\n"
"--\n"
"drop table if exists xdb_xfile;\n"
"drop table if exists xdb_xname;\n"
"drop table if exists xdb_xdata;\n"
"\n"
"-- glusterfs files\n"
"create table xdb_xfile (\n"
"	fid	integer not null,\n"
"	gfid	text not null,\n"
"	path	text not null,\n"
"	name	text not null,\n"
"\n"
"	primary key (fid),\n"
"	unique (gfid)\n"
");\n"
"\n"
"-- file attributes (only names), including stat(2) and xattrs\n"
"create table xdb_xname (\n"
"	nid	integer not null,\n"
"	name	text not null,\n"
"\n"
"	primary key (nid)\n"
");\n"
"\n"
"-- stat(2) attributes\n"
"insert into xdb_xname (name) values ('st_dev');\n"
"insert into xdb_xname (name) values ('st_ino');\n"
"insert into xdb_xname (name) values ('st_mode');\n"
"insert into xdb_xname (name) values ('st_nlink');\n"
"insert into xdb_xname (name) values ('st_uid');\n"
"insert into xdb_xname (name) values ('st_gid');\n"
"insert into xdb_xname (name) values ('st_rdev');\n"
"insert into xdb_xname (name) values ('st_size');\n"
"insert into xdb_xname (name) values ('st_blksize');\n"
"insert into xdb_xname (name) values ('st_blocks');\n"
"insert into xdb_xname (name) values ('st_atime');\n"
"insert into xdb_xname (name) values ('st_mtime');\n"
"insert into xdb_xname (name) values ('st_ctime');\n"
"\n"
"create index ix_xdb_xname_name on xdb_xname (name);\n"
"\n"
"-- file/attributes/values relations\n"
"create table xdb_xdata (\n"
"	xid	integer not null,\n"
"	fid	integer not null references xdb_xfile (fid),\n"
"	nid	integer not null references xdb_attr (nid),\n"
"	ival	integer,\n"
"	sval	text,\n"
"\n"
"	unique (fid, nid),\n"
"	primary key (xid)\n"
");\n"
"\n"
"-- upon unlinking the file entry, remove all xdata entries.\n"
"-- keep the xname entries for later (possible) hits.\n"
"-- using before trigger would be safe, as long as it doesn't touch the row\n"
"-- which is to be affected.\n"
"-- more at: https://sqlite.org/lang_createtrigger.html\n"
"create trigger tr_xdb_xfile_unlink before delete on xdb_xfile\n"
"	begin\n"
"		delete from xdb_xdata where xdb_xdata.fid = OLD.fid;\n"
"	end;\n"
"\n"
"create index ix_xdb_xdata_ival on xdb_xdata (nid, ival);\n"
"create index ix_xdb_xdata_sval on xdb_xdata (nid, sval);\n"
"\n"
;
